post_list:
  path: /
  methods: ['GET']
  controller: App\Controller\PostController::list

post_show:
  path: /{id}
  controller: App\Controller\PostController::show
  methods: ['GET']
  requirements:
    id: '\d+'
    _format: json

post_edit:
  path: /edit/{id}
  controller: App\Controller\PostController::edit
